# Generated by Django 4.2 on 2025-03-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
