# Generated by Django 4.2 on 2025-03-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_contactus_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
