# Generated by Django 4.2 on 2025-03-28 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_contactus_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="replied_to",
        ),
        migrations.AddField(
            model_name="contactus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactus",
            name="replied_to_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
