# Generated by Django 4.2 on 2025-03-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "communications",
            "0004_remove_contactus_replied_to_contactus_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "Contact Us Messages"},
        ),
    ]
