# Generated by Django 4.2 on 2025-04-03 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communications", "0007_customorderrequest_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customorderrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_order_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
