# Generated by Django 4.2 on 2025-04-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0008_alter_customorderrequest_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("added_to_list", models.BooleanField(default=False)),
            ],
        ),
    ]
