# Generated by Django 4.2 on 2025-04-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0009_newslettersignup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsletterSignup",
        ),
    ]
