# Generated by Django 4.2 on 2025-04-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0010_delete_newslettersignup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("specifics", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("publish", models.BooleanField(default=False)),
            ],
        ),
    ]
