# Generated by Django 4.2 on 2025-04-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0011_events"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
    ]
