# Generated by Django 4.2 on 2025-04-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0012_rename_events_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="free_entrance",
            field=models.BooleanField(default=False),
        ),
    ]
