# Generated by Django 4.2 on 2025-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0013_event_free_entrance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="phone",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
