# Generated by Django 4.2 on 2025-04-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0014_alter_contactus_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
