# Generated by Django 4.2 on 2025-03-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=254)),
                ("dimensions", models.CharField(max_length=254)),
                ("note", models.CharField(blank=True, max_length=254, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="artworks.artist",
                    ),
                ),
                (
                    "medium",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="artworks.medium",
                    ),
                ),
            ],
        ),
    ]
