# Generated by Django 4.2 on 2025-03-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0002_artwork"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "For sale"),
                    (2, "Sold"),
                    (3, "Pending"),
                    (4, "On temporary hold"),
                ],
                default=3,
            ),
        ),
    ]
