# Generated by Django 4.2 on 2025-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0003_artwork_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="note",
        ),
        migrations.AddField(
            model_name="artwork",
            name="custom_made",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "for_sale"), (2, "sold")], default=3
            ),
        ),
    ]
