# Generated by Django 4.2 on 2025-03-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0004_remove_artwork_note_artwork_custom_made_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "for_sale"), (2, "sold")], default=1
            ),
        ),
    ]
