# Generated by Django 4.2 on 2025-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0005_alter_artwork_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="image_alt",
            field=models.CharField(default="Image of the artist", max_length=254),
        ),
    ]
