# Generated by Django 4.2 on 2025-03-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0006_artist_image_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="alt_image",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
