# Generated by Django 4.2 on 2025-03-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0007_artwork_alt_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artwork",
            old_name="alt_image",
            new_name="image_alt",
        ),
    ]
