# Generated by Django 4.2 on 2025-03-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0010_artist_mini_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "for_sale"), (2, "sold"), (3, "pending")], default=1
            ),
        ),
    ]
