# Generated by Django 4.2 on 2025-04-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0012_artist_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="selfie",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="selfie_url",
            new_name="image_url",
        ),
    ]
