# Generated by Django 4.2 on 2025-04-03 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artworks", "0013_rename_selfie_artist_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="custom_orderer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
