# Generated by Django 4.2 on 2025-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0014_artwork_custom_orderer"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="free_entrance",
            field=models.BooleanField(default=True),
        ),
    ]
