# Generated by Django 4.2 on 2025-04-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0015_artwork_free_entrance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="free_entrance",
        ),
    ]
