# Generated by Django 4.2 on 2025-04-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0016_remove_artwork_free_entrance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="image_url",
        ),
    ]
