# Generated by Django 4.2 on 2025-04-13 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0017_remove_artist_image_url_remove_artwork_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="art",
                to="artworks.artist",
            ),
        ),
    ]
