# Generated by Django 4.2 on 2025-03-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artworks", "0009_alter_artwork_artist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(editable=False, max_length=32)),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("street_address1", models.CharField(max_length=80)),
                (
                    "street_address2",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("town_or_city", models.CharField(max_length=50)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                ("county", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "order_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "lineitem_total",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=7),
                ),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artworks.artwork",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineitems",
                        to="checkout.order",
                    ),
                ),
            ],
        ),
    ]
