# Generated by Django 4.2 on 2025-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
