# Generated by Django 4.2 on 2025-03-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_alter_orderlineitem_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="county",
            new_name="state",
        ),
    ]
