# Generated by Django 4.2 on 2025-03-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_rename_county_order_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="country",
        ),
    ]
