# Generated by Django 4.2 on 2025-03-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_remove_order_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(default="US", max_length=50),
            preserve_default=False,
        ),
    ]
