# Generated by Django 4.2 on 2025-03-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0005_order_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="original_cart",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(default="", max_length=254),
        ),
    ]
